### ISSUE TITLE
update technical vignette for the MPG algorithm

### ISSUE THREAD

**Issue by achubaty** [achubaty/grainscape#15]
started, see [MPG_algorithm.Rmd](https://github.com/achubaty/grainscape2/blob/master/vignettes/MPG_algorithm.Rmd)

**Comment by achubaty** [comment]
re: voronoi calculation, how does our approach compare to `dismo::voronoi`? obviously, their approach uses single points instead of patches, but is the algorithm similar?

```r
p <- matrix(c(17, 42, 85, 70, 19, 53, 26, 84, 84, 46, 48, 85, 4, 95, 48, 54, 66, 74, 50, 48, 
            28, 73, 38, 56, 43, 29, 63, 22, 46, 45, 7, 60, 46, 34, 14, 51, 70, 31, 39, 26), ncol = 2)
v <- dismo::voronoi(p)
plot(v)
points(p)
```

**Comment by achubaty** [comment]
Fall *et al.* (2007) describes the core features/definitions of the MPG etc., which would be useful for a high-level overview of what our algorithm does.

**Comment by ecologics** [comment]
Absolutely.  Fall et al. (2007) is the only place in which the MPG is fully documented.  There are several places where the GOC is fully documented.  I have referenced all of these in the new vignette.

**Comment by achubaty** [comment]
updated with MS submission
