### ISSUE TITLE
GOC() and visualize() with doThresh= parameter have no standardized way to reference the GOC threshold

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#26]
For example:

``` R
tiny <- raster(system.file("extdata/tiny.asc", package = "grainscape"))
tinyCost <- reclassify(tiny, rcl = cbind(c(1, 2, 3, 4), c(1, 5, 10, 12)))
tinyPatchMPG <- MPG(cost = tinyCost, patch = (tinyCost == 1))

## Extract a GOC for only one threshold given the doThresh option
## Here doThresh references the threshold value in resistance units
tinyPatchGOC <- GOC(tinyPatchMPG, doThresh = 21)

## FAILS
visualize(tinyPatchGOC, whichThresh = 21)

## WORKS because it is the first and only indexed
## threshold produced bu GOC()
visualize(tinyPatchGOC, whichThresh = 1)
```

Need some way to deal with this.

**Comment by achubaty** [comment]
@ecologics this now works:

```r
library(raster)

tiny <- raster(system.file("extdata/tiny.asc", package = "grainscape"))
tinyCost <- reclassify(tiny, rcl = cbind(c(1, 2, 3, 4), c(1, 5, 10, 12)))
tinyPatchMPG <- MPG(cost = tinyCost, patch = tinyCost == 1)

## Extract a GOC for only one threshold given the doThresh option
## Here doThresh references the threshold value in resistance units
tinyPatchGOC <- GOC(tinyPatchMPG, doThresh = 21)

## WORKS
visualize(tinyPatchGOC, whichThresh = 21)
```

**Comment by achubaty** [comment]
@ecologics and an example using `nThresh`:

```r
library(raster)

tiny <- raster(system.file("extdata/tiny.asc", package = "grainscape"))
tinyCost <- reclassify(tiny, rcl = cbind(c(1, 2, 3, 4), c(1, 5, 10, 12)))
tinyPatchMPG <- MPG(cost = tinyCost, patch = tinyCost == 1)

## Extract a GOC for only one threshold given the doThresh option
## Here doThresh references the threshold value in resistance units
tinyPatchGOC <- GOC(tinyPatchMPG, nThresh = 4)

## look at the maxLink column for possible whichThresh values
tinyPatchGOC@summary ## 0, 35, 64, 114

## WORKS
visualize(tinyPatchGOC, whichThresh = 35)
```

**Comment by ecologics** [comment]
@achubaty this is fabulous. 
    
    Will nThresh still work.  Say, if we don't know exactly which
      thresholds to use, but just want a bunch of them.  Or do we need
      to think about a better interface to this.  Perhaps a helper
      function such as findthresh(n) that generates a vector sequence
      for doThresh.  So you could call 
    
    `GOC(..., doThresh=findthresh(10))`
    or something like that.
    Thoughts?
    
    
    
      --
      Paul Galpern, Ph.D.
        Landscape | Ecology | Informatics
        Assistant Professor | University of Calgary
        Faculty of Environmental Design (primary)
        Department of Biological Sciences (adjunct)
        o: 403.220.7436 | m: 403.614.9331
        w: ecologics.ucalgary.ca
        
       
    On 07/03/2017 3:22 PM, Alex Chubaty
      wrote:
    
    
      
      @ecologics this now works:
      
        library(raster)

tiny <- raster(system.file("extdata/tiny.asc", package = "grainscape"))
tinyCost <- reclassify(tiny, rcl = cbind(c(1, 2, 3, 4), c(1, 5, 10, 12)))
tinyPatchMPG <- MPG(cost = tinyCost, patch = tinyCost == 1)

## Extract a GOC for only one threshold given the doThresh option
## Here doThresh references the threshold value in resistance units
tinyPatchGOC <- GOC(tinyPatchMPG, doThresh = 21)

## WORKS
visualize(tinyPatchGOC, whichThresh = 21)
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
          
          
        
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/achubaty/grainscape","title":"achubaty/grainscape","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/achubaty/grainscape"}},"updates":{"snippets":[{"icon":"PERSON","message":"@achubaty in #26: @ecologics this now works:\r\n\r\n```r\r\nlibrary(raster)\r\n\r\ntiny \u003c- raster(system.file(\"extdata/tiny.asc\", package = \"grainscape\"))\r\ntinyCost \u003c- reclassify(tiny, rcl = cbind(c(1, 2, 3, 4), c(1, 5, 10, 12)))\r\ntinyPatchMPG \u003c- MPG(cost = tinyCost, patch = tinyCost == 1)\r\n\r\n## Extract a GOC for only one threshold given the doThresh option\r\n## Here doThresh references the threshold value in resistance units\r\ntinyPatchGOC \u003c- GOC(tinyPatchMPG, doThresh = 21)\r\n\r\n## WORKS\r\nvisualize(tinyPatchGOC, whichThresh = 21)\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/achubaty/grainscape/issues/26#issuecomment-284879505"}}}

**Comment by achubaty** [comment]
hmm looks like this is not as simple a tweak as I first thought.

my 'fix' doesn't work for the example in Tutorial 2 of the vignette :cry:

**Comment by achubaty** [comment]
> hmm looks like this is not as simple a tweak as I first thought.
>
> my 'fix' doesn't work for the example in Tutorial 2 of the vignette :cry: 

hmmm this looks like it may be a bug with `GOC`...

**Comment by achubaty** [comment]
I totally missed the `GOC` piece previously and I've reverted the commit where I thought I fixed this, and am reworking it, which will solve the issues in the vignette.

**Comment by achubaty** [comment]
reworked so that the `id` of the threshold (*i.e.*, the index into the full list of objects) is stored as the first column of the `summary` data.frame in the `goc` object.
