### ISSUE TITLE
rename visualize() and create plot() method for 'goc' objects

### ISSUE THREAD

**Issue by achubaty** [achubaty/grainscape#30]
Can `visualize` be replaced with a `plot` method for `goc` objects?

**Comment by achubaty** [comment]
@ecologics suggestions for a more meaningful name for `visualize`?

**Comment by ecologics** [comment]
@achubaty how about `grain()` because it is really just about
      extracting a single grain, and not actually plotting it.  You
      could then use `plot(grain(myGOC, whichThresh=x))`
    
    
    
      --
      Paul Galpern, Ph.D.
        Landscape | Ecology | Informatics
        Assistant Professor | University of Calgary
        Faculty of Environmental Design (primary)
        Department of Biological Sciences (adjunct)
        o: 403.220.7436 | m: 403.614.9331
        w: ecologics.ucalgary.ca
        
       
    On 07/03/2017 3:31 PM, Alex Chubaty
      wrote:
    
    
      
      @ecologics suggestions for a more
        meaningful name for visualize?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
          
          
        
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/achubaty/grainscape","title":"achubaty/grainscape","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/achubaty/grainscape"}},"updates":{"snippets":[{"icon":"PERSON","message":"@achubaty in #30: @ecologics suggestions for a more meaningful name for `visualize`?"}],"action":{"name":"View Issue","url":"https://github.com/achubaty/grainscape/issues/30#issuecomment-284881861"}}}

**Comment by achubaty** [comment]
sounds good. `grain` it shall be.
