### ISSUE TITLE
Remove GOC(..., sp=TRUE) option

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#38]
This uses the `raster` function `rasterToPolygon()` which is based on an `rgeos` function which has long been known to have  memory leak.  I woul dhave hoped that newer versions of the `GEOS` library would have fixed this problem.  But all in vina.

Indeed use of this function ever since I developed this several years ago always consumes all available memory.  

Quite simply we will need to remove this functionality from the `GOC()` function because it doesn't work.  It's too bad as it creates really great visualizations if you can coax it into operation.  A test I ran last night blew up on a moderate raster (2000 x 3000 cells).

**Comment by ecologics** [comment]
gdal_polygonizer.py will do reliably and at lightning speed, apparently, but it also requires the user to have the GDAL library installed (not just `rgdal`), as well as python, and gets called via the command line.  This is not a good thing to include in a package.

I am currently working on an alternative that uses `raster::boundaries(..., class=TRUE)` to find the edges of the voronoi polygons.  This happens very quickly and will allow plotting of the voronoi boundaries in a different colour.  While it doesn't render well at all in R, it is fine in other GIS software.

**Comment by achubaty** [comment]
check out the [`gdalUtils`](https://cran.r-project.org/package=gdalUtils) package to see whether `gdal_polygonizer.py` is included.

**Comment by ecologics** [comment]
Just checked out `gdalUtils` unfortunately it does not include a polygonizer.  Not sure that it would be a good idea though to include a package like this that will require hard to install external software.

**Comment by ecologics** [comment]
I am proposing that we remove the emphasis from doing visualizations of these products in R, and rather improve the capacity to export visualization-ready products (e.g. for use in QGIS or ArcMap).  R is just not good for visualizing geographic data, and we might as well not fight with it.

See other issue suggesting a new function called `export()`.
