### ISSUE TITLE
Create a patchfilter() function

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#40]
That will remove patches smaller than a threshold number of pixels (or area) and could be called as follows `MPG(costRas, patch=patchfilter(patchRas))`.

This may be important, as very tiny patches can make visualizations hard to understand, and they don't always behave nicely. For example, single pixel patches can be orphaned when surrounded (mostly) by NAs.  This can also make things a little bit nonintuitive..

**Comment by achubaty** [comment]
related to #29

**Comment by achubaty** [comment]
note this was renamed `patchFilter` in the linked commit above
