### ISSUE TITLE
Parks and protected areas vignette

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#41]
A vignette of how you might use `MPG()` and `GOC()` in a parks and protected area connectivity scenario.  Ideally this would also be supplementary material on a publication on this software.

**Comment by ecologics** [comment]
I propose to incorporate a couple of figures in to the main text that illustrate an MPG and a GOC on a parks and protected area scenario.  Perhaps a three panel figure:  (a) Resistance surface of PAs in BC;  (b) MPG of PAs in BC; and (c) GOC of PAs in BC.

There is now a rather long vignette that covers almost every scenario, and includes code.  I think this is not going to add much as its own vignette.

**Comment by achubaty** [comment]
ok, we won't do a vignette on this. closing.
