### ISSUE TITLE
Create a visualize() function that produces ggplot2 objects

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#42]
Use the `ggnetwork` package which is designed for creating network visualizations as `ggplot2` objects.  It has `geom_edges()` and `geom_nodes()` geoms.  It also has a `fortify.network()` function that calls another package.  It is not especially useful for spatially-referenced networks (such as these), but when a `fortify.network(..., layout=data.frame(xcoord, ycoord))` call is passed to it it will lay out the nodes according to their actual coordinates, rather than coordinates that correspond to some node layout algorithm.  

However there appear to be some bugs or annoyances with the `ggnetwork` workflow.  So creating a tight `visualize()` function that produces a `ggplot2` object and deals with these, is probably necessary.

Ideally the `visualize()` function should:

- Have a synonym `visualise()` to work for those in the UK
- Work with output of `grain()` as well as `MPG` objects.
- Have an example showing how  a `geom_raster()` or `geom_tile()` of a patch raster could also be added to the plot

Note that briefly there was a `visualize()` function and a `gsGOCVisualize` function and that these were deprecated.  This function will have completely different functionality, and is unlikely to cause problems among users as `visualize()` was only temporarily in use (and not on the RForge release).

**Comment by achubaty** [comment]
if this is all about plotting, why not create the appropriate `plot` methods for these objects instead?

**Comment by achubaty** [comment]
likewise we can create `ggplot` equivalent methods if we want to go the `gg` route

**Comment by ecologics** [comment]
Good points.  Maybe me just want some kind of fortify function that prepares it for use with `ggplot2` rather than creating visualization tools.  

It really sends us down a rather wandering path, I suppose to create functions that hide the `ggplot` functionality.  Although I have seen examples of this in several packages where some function converts the package-specific objects into a `ggplot` and returns it for additional modifications.

**Comment by ecologics** [comment]
I would consider now closing this issue.  I think we should emphasize that most practical applications of this tool will require GIS-based visualization and not R-based visualization.  As such developing these tools extensively is probably not useful.

R has not been designed to plot large rasters well.  Neither `raster::plot` nor `ggplot2::geom_raster()` can do this with sufficient resolution for it to be useful to anyone.
