### ISSUE TITLE
Remove `corridor()` function

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#44]
This was an interesting idea to develop several years ago, but it really needs to be motivated properly in its own paper.  I think for the time being we should not prioritize its development and exclude it from the initial presentation of this software.

We can either remove it, or classify it as an experimental function and not draw attention to it in vignettes, or manuscripts.  At best it is experimental.

**Comment by achubaty** [comment]
Let's not remove it, but certainly we can consider it a work in progress.

**Comment by ecologics** [comment]
We think now that we'll keep this in.  Verify that corridor() works well.

**Comment by achubaty** [comment]
I just dealt with creating a new `corridor` object and plotting (see #33) and I think this function works well now that the previous `GOC` bug(s) were fixed.
