### ISSUE TITLE
Add warnings in MPG() about patch size

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#45]
Consider adding warnings in `MPG()` around line 168 if any of the `patchArea` sizes are 1 cell in size. 

While these still work, it may be useful for the user to know this and be encouraged to filter them out for improved interpretability of the output.

For example:
```r
warning('grainscape:  Patches of only 1 pixel in size are present. You may wish to remove them to improve interpretation of your connectivity models.  Use patchfilter() to do this.')
```

**Comment by achubaty** [comment]
a `message` might be better for this. easy to `suppressMessages()` as needed; whereas if a user does `suppressWarnings()` it could mute legit warnings. also consider adding a `quiet` argument to this (and any other functions that provide messages).

**Comment by ecologics** [comment]
Checking for single cell patches on very large rasters is going to take a long time.  In turn running rasters in grainscape that are very large and have lots of patches is also going to take a very long time.  I am not sure warning is going to work.

I propose to close this issue.

**Comment by achubaty** [comment]
fine by me. we can include a note in the documentation/vignette-/examples about filtering patches.
