### ISSUE TITLE
Implement two simple ggplotting helpers

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#47]
I am going back and forth on this.  I think a middle ground is appropriate.

I propose the following:

A new function called `ggGS()` which is very simple.  It will take either an `MPG` or `grain` object and a second parameter with the slot name, and possibly a third parameter. 

 If it is a raster it will prep that raster by turning it into a `data.frame` with columns `x`, `y`, and `value` so that it can be used with `geom_raster()` in `ggplot2` as follows:

```r
ggplot() + geom_raster(ggGS(myMPG, "patchId"), aes(x=x, y=y, fill=value)
```

If it is an `igraph` object and a `type` parameter `='node'` it will produce a `data.frame` with the nodes and attributes.  If `type='link'` it will produce a `data.frame` with the links, their endpoints and attributes.  For example:

```r
ggplot() + geom_segment(ggGS(myMPG, "mpg", "link"), aes( ...)) # etc
```

In this sense it is basically a fortify tool for tidying objects for ggplotting.

When this functionality is developed, it will be simple to create a `plot()` for class `MPG` and `grain` that takes a second variable specifying the type of plot.  It will then wrap these calls to produce canned quick visualizations with various other elements (e.g. themes, scales and layouts) preset for a fast look at the state of the data.

**Comment by ecologics** [comment]
Motivated to do this because ggplot actually produces *better* visualizations than base plot of rasters.  I hadn't realized this.

See below made as follows:
`ggplot() + geom_raster(data=ggS(resistance), aes(x=x, y=y, fill=value))  + ggthemes::theme_map() + scale_fill_distiller(palette="PRGn")`
 
![image](https://user-images.githubusercontent.com/17838640/28217978-58018a10-6874-11e7-9a32-175e06dd3b79.png)

**Comment by achubaty** [comment]
sounds reasonable. maybe this is a two-step implementation:

1. create a `fortify` method for gs objects;
2. create the `gg_grain` or whatever method for producing the ggplot object.

**Comment by achubaty** [comment]
sidenote: the `rasterVis` package also produces better raster visualizations than base plot.

**Comment by ecologics** [comment]
I think a `fortify` kind of approach is a good idea.  I am tempted to not do `gg_grain` as would like to leverage existing `gplot` methods to give the user the maximum flexibility (and familiarity) with plotting.

**Comment by achubaty** [comment]
ok. As long as the `fortify` method handles the complexity of extracting the correct slot in the grain and mpg objects, the user doesn't need to understand their structure (and that of S4 objects more generally).

the output of `fortify` can then be easily passed to ggplot

**Comment by ecologics** [comment]
Hmm, not sure I want to design a function like `fortify` that is fully compliant with other `fortify` methods in other packages.  Sounds like a high bar to achieve.  Really just want a function to pre-process data. We already have a `graphdf` function which achieves a similar outcome to fortify.  But it will not prep data for plotting, as yet.

**Comment by achubaty** [comment]
what needs to be done to either extend `graphdf` to do the fortifying (and perhaps rename `graphdf`)?
alternatively, keep `graphdf` as is but using it within the `fortify` method can work. what are the extra pieces that are "too high to achieve"? I can help with the implementation.

**Comment by achubaty** [comment]
but see: https://stackoverflow.com/questions/34543468/successor-to-ggplot2fortify

indeed, `?ggplot2::fortify` shows that it may be deprecated soon (but for now it isn't, so we can still use it until we find a better approach)

**Comment by ecologics** [comment]
Basically it appears that the new `fortify` would need to be `tidy` in the format of the `broom` package.

The problem is it is not really about tidying the data.  For igraph objects--yes.  But for rasters it is just about automating a change in their data structure to work with ggplot.  I think avoiding any comparisons to `tidy` or `fortify` might actually be more transparent.

**Comment by ecologics** [comment]
Going to proceed with `ggGSPrep()` for now, with functionality as described above.

**Comment by ecologics** [comment]
Let me know what you think of the new function `ggGS()`.  Going to now wrap `plot()` methods around this for quick visualizations of objects.  Emphasizing the use of `ggGS()` for more control and customized visualizations.

**Comment by achubaty** [comment]
i'm just pushing the last of my cleanup/fixes. please make sure you are up to date before making further changes
