### ISSUE TITLE
update intro/tutorial vignette

### ISSUE THREAD

**Issue by achubaty** [achubaty/grainscape#5]
- [x] create `.Rmd` version, which can easily be updated and rebuilt. @ecologics do you have the (sweave?) source file used to build the original vignette pdf?
- [x] update vignette content (_e.g._, remove SELES and 'Windows only' references)
- [x] change `grainscape` to `grainscape2`
- [x] load all required packages (they are in Imports instead of Depends)
- [x] Commit 94d87cc48ecb2e44c3ef73342bcf316cf2d0f843 temporarily adds the `--no-build-vignette` option to the RStudio project for building & checking. This needs to be reverted once the vignette has been updated. (reverted with 0e05af586bc96d620344be922caaa05880b48210.)
### problems building vignette:

I haven't looked at everything in detail, so I'm sure there are other problems not listed here.
To debug these, we should start with the first functions in the sequence (`gsMPG()` and `gsGOC()`) to make sure they are correct before attempting to debug the others.
- [x] lots of warnings: `NAs introduced by coercion` (see #14)
- [ ] **Tutorial 1, Step 3:** not all links in the original version of figure 2 appear in the update version.
- [ ] **Tutorial 1, Step 5:** scalar analysis outputs don't match, including Figure 3.
- [ ] **Tutorial 2, Step 4:** different tessellations produced in figure 6 (`gsGOCVisualize`).
- [ ] **Tutorial 2, Step 6:** different values output from `gsGOCDistance`.
- [ ] **Tutorial 3, Step 1:** from the text, `max(patchyMPGLattice$patchId[], na.rm = TRUE)` should return `100`, but it returns `104`.
- [ ] **Tutorial 3, Step 3:** figure 7, showing the lattice links is totally different in the updated vignette.
- [ ] **Tutorial 4, Section 2:** `gsGOCCorridor` figure 10 shows different links and a different shortest path.
- [ ] **Tutorial 4, Section 2:** figure 11 shows different tesselation, links, and a different shortest path.
- [ ] **Tutorial 4, Section 2:** figure 12 shows different tessellation and different shortest path.

In the voronoi plots, the colours make it difficult to see how different the plots are in each vignette.

**NOTE:** I've temporarily commented out the following chunks that fails:
- [x] **Tutorial 1, Step 6:** raster `patchyMPG$lcpPerimWeight` used to create raster `thresholdLink` contains values between 201-810, none of which are `<=200` specified to create the latter, resulting in a raster of all `NA`s, causing the plot to fail. *UPDATE* follwing bug fix for #32, now runs without error.

**Comment by ecologics** [comment]
Tutorial / vignette is being completely rewritten as a reference to the types of analyses that can be done with `grainscape`.  The old vignette could be removed.  It should be finished in the next few days.

**Comment by achubaty** [comment]
rewrite completed with:

- a3bb96e23e8efc1b84b515db65895be580310791
- aa2d5d2cca0d9c5bd06d6628fc5bdcd075223303
- 5efe7a37ac5a60339ce87f6402af309fa1046639
- f26df03e7ec27c977530092aef2185a1f0785dee

further tweaking may be necessary, but I'm closing this issue
