### ISSUE TITLE
Unexpected plot() behaviour with lattice MPG()

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#51]
If you extract an MPG and plot it using default data, everything works.
```
tiny <- raster::raster(system.file("extdata/tiny.asc", package = "grainscape"))
tinyCost <- raster::reclassify(tiny, rcl = cbind(c(1, 2, 3, 4), c(1, 5, 10, 12)))
tinyPatchMPG <- MPG(cost = tinyCost, patch = (tinyCost == 1))

## Now plot using the default (quick='mpgPerimPlot')
plot(tinyPatchMPG)
```
Looks great!
![image](https://user-images.githubusercontent.com/17838640/28278109-2ccd727a-6ad9-11e7-9990-90342f9801f4.png)

Now use lattice MPG
```
tinyLatticeMPG <- MPG(cost=tinyCost, patch=10)
plot(tinyLatticeMPG)
```
The resulting background is all grey, suggesting that it has all become patch.  Not sure where this is happening.  If it has something to do with how lattice MPGs are dealt with by the `MPG()` function that is leading to downstream plotting differences.  It should have the same green lines but single pixel grey points at nodes of the lattice.
![image](https://user-images.githubusercontent.com/17838640/28278189-72fc25d4-6ad9-11e7-934d-1bf51049cb15.png)

**Comment by ecologics** [comment]
This happens because of how `ggplot` and `geom_raster()` handle equally scaled data like this on a lattice.  Because the coordinates are equally spaced it just makes the cell size huge.  Here is a way to trick it, but this is is unsatisfactory.  There has to be a less hacky way:

```
ggplot() + geom_raster(data=rbind(ggGS(tinyLatticeMPG, "patchId"), data.frame(value=0, x=1:100, y=1), cbind(value=0, x=1, y=1:100)), 
aes(x=x, y=y, fill=value > 0)) +
 scale_fill_manual(values=c("white", "grey"))  + 
geom_segment(data=ggGS(tinyLatticeMPG, "links"),
         aes(x = x1p, y = y1p, xend = x2p, yend = y2p, colour = "forestgreen")) +
         scale_colour_identity()
```
![image](https://user-images.githubusercontent.com/17838640/28279677-75894408-6ade-11e7-9566-6838a1b7ce5a.png)

**Comment by ecologics** [comment]
Not sure how important this actually is, as it is not that likely that you would want to visualize a lattice in this manner.  But nonetheless it is a bug.

**Comment by achubaty** [comment]
related to #63 ?

**Comment by achubaty** [comment]
fixed based on above. I couldn't find a way to do this without filling in x and y with 0 values and plotting those with transparent colour.

![image](https://user-images.githubusercontent.com/3435577/233214217-53cc3415-0d5c-440f-bb33-f7ec0627ffd1.png)
