### ISSUE TITLE
Retitle package

### ISSUE THREAD

**Issue by ecologics** [achubaty/grainscape#52]
Currently the title of the package is `Grains of connectivity and minimum planar graph modelling of landscape connectivity.`

I think we should rename this to emphasize the applications and not the methods, which are going to be obscure.

Both the package and the paper could be:  `grainscape:  Efficient modelling of landscape connectivity, habitat and protected area networks in R.`

**Comment by achubaty** [comment]
note that, per CRAN, the package name cannot be in the title (and I don't think 'R' can/should be either). Also, the title needs to be in title case.

Thus, the package title should be changed to "Efficient Modelling of Landscape Connectivity, Habitat, and Protected Area Networks"
