### ISSUE TITLE
vignette is too big

### ISSUE THREAD

**Issue by achubaty** [achubaty/grainscape#53]
```r
* checking sizes of PDF files under ‘inst/doc’ ... WARNING
  ‘gs+qpdf’ made some significant size reductions:
     compacted ‘grainscape_vignette.pdf’ from 1.8Mb to 1.2Mb
  consider running tools::compactPDF(gs_quality = "ebook") on these files
```

**Comment by ecologics** [comment]
Seriously!  That's annoying.  Hopefully it can be addressed with this tool!  I don't want to carve out any content.

**Comment by achubaty** [comment]
I'm looking to see if there's an issue with the way the figures are being included -- you insert the pngs from file rather than using the plots generated by R directly. By not using the pngs, vignette size drops to ~400MB.

**Comment by ecologics** [comment]
Hopefully you mean 400KB.  Another approach is to lower the dpi to 300, but this would also require tweaking the base font size settings (perhaps in ggplot!?)

**Comment by achubaty** [comment]
ha! yes, I meant 400 kB

**Comment by achubaty** [comment]
warning re: PDF size now gone with f26df03e7ec27c977530092aef2185a1f0785dee, where I removed the use of `png`s  for figs 9-25. closing.
