### ISSUE TITLE
grainscape vulnerable to forthcoming changes in sp and rgdal

### ISSUE THREAD

**Issue by rsbivand** [achubaty/grainscape#65]
Running revdep checks for current rgdal on R-Forge - see:

https://stat.ethz.ch/pipermail/r-sig-geo/2019-November/027801.html

shows the errors in the attached check log, related to use of PROJ&/GDAL3
and required changes to sp and rgdal. If useful find a regerence to a docker
image in this thread:

https://github.com/r-spatial/discuss/issues/28

Changes will occur quite fast, and packages need to be prepared. Note the descriptions given about major changes to the sp CRS object which do not affect package authors who have treated the CRS object carefully, with changes biting. A guess might be that lines like: `projection(linksCentrSP) <- CRS(projection(x@patchId))` using the **raster** form may be vurlnerable, but I can't debug everything. With "new" **sp** and **rgdal**, `CRS()` does a lookup using the PROJ string to retrieve a WKT2 string that is added to the CRS object as a comment. I think that **raster**'s `crs()` and `projection()` and their assignment functions should be avoided (until they have been brought into line with **sp**, and certainly stop accessing S4 slots using `@`.

Ping: @rhijmans, probably needs a **raster** release to catch up with **sp** 1.3-3 on my github fork and **rgdal** 1.5-1 on R-Forge.
```
* checking examples ... ERROR
Running examples in ‘grainscape-Ex.R’ failed
The error most likely occurred in:

> ### Name: export
> ### Title: Export spatial data from MPG and GOC models
> ### Aliases: export export,mpg-method export,grain-method export,goc-method
> 
> ### ** Examples
> 
> ## Load raster landscape
> tiny <- raster::raster(system.file("extdata/tiny.asc", package = "grainscape"))
> 
> ## Create a resistance surface from a raster using an is-becomes reclassification
> tinyCost <- raster::reclassify(tiny, rcl = cbind(c(1, 2, 3, 4), c(1, 5, 10, 12)))
> 
> ## Produce a patch-based MPG where patches are resistance features=1
> tinyPatchMPG <- MPG(cost = tinyCost, patch = tinyCost == 1)
> 
> ## Extract a representative subset of 5 grains of connectivity
> tinyPatchGOC <- GOC(tinyPatchMPG, nThresh = 5)
> 
> ## Export raster and vectors of a grain to a specified directory
> tmpdir <- tempdir()
> export(grain(tinyPatchGOC, 2), dirname = "tiny_goc_thresh2", path = tmpdir)
Error in writeOGR(sp, dsn = dirpath, layer = fname, driver = "ESRI Shapefile",  : 
  Can't parse WKT2-style parameter string
Calls: export -> export -> .wShp -> writeOGR
Execution halted
```

**Comment by achubaty** [comment]
Testing on recent R-devel with development version of `rgdal`:

```r
── R CMD check results ─────────────────────────────────── grainscape 0.4.3 ────
Duration: 6m 18.5s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔
> R.version
               _                                                 
platform       x86_64-pc-linux-gnu                               
arch           x86_64                                            
os             linux-gnu                                         
system         x86_64, linux-gnu                                 
status         Under development (unstable)                      
major          4                                                 
minor          1.0                                               
year           2020                                              
month          04                                                
day            07                                                
svn rev        78170                                             
language       R                                                 
version.string R Under development (unstable) (2020-04-07 r78170)
nickname       Unsuffered Consequences                           
> packageVersion("sp")
[1] ‘1.4.1’
> packageVersion("raster")
[1] ‘3.0.12’
> packageVersion("rgdal")
[1] ‘1.5.6’
> amc::pkgSrc(c('sp', 'raster', 'rgdal'))
                   sp                raster                 rgdal 
               "CRAN"                "CRAN" "rforge/rgdal@master" 
```

I'll leave this issue open for now, but it looks like upstream package maintainers have done the hard work to maintain compatibility. :smile:

**Comment by rsbivand** [comment]
Please report rgdal_extSoftVersion(), it is their versions that bite. If on
GDAL>=3 and PROJ >=6, then clean, otherwise unknown.

Roger Bivand
Falsensvei 32
5063 Bergen

tir. 7. apr. 2020, 22.32 skrev Alex Chubaty <notifications@github.com>:

**Comment by achubaty** [comment]
@rsbivand good point, sorry. I will fire up a docker container with those newer versions and retest.

**Comment by achubaty** [comment]
Using the `sf` GDAL Docker image as a starting point, I ran checks, which came back clean:

```r
-- R CMD check results ----------------------------------- grainscape 0.4.3 ----
Duration: 3m 2.1s

> checking examples ... WARNING
  checking a package with encoding  'UTF-8'  in an ASCII locale

0 errors v | 1 warning x | 0 notes v
```
I believe I can safely ignore the locale warning.

**Comment by achubaty** [comment]
all good when I changed the locale:

```r
-- R CMD check results ----------------------------------- grainscape 0.4.3 ----
Duration: 3m 9.8s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

> packageVersion("sp")
[1] ‘1.4.1’
> packageVersion("raster")
[1] ‘3.0.12’
> packageVersion("rgdal")
[1] ‘1.5.6’
> amc::pkgSrc(c('sp', 'raster', 'rgdal'))
       sp    raster     rgdal 
   "CRAN"    "CRAN" "R-Forge" 
> rgdal::rgdal_extSoftVersion()
          GDAL GDAL_with_GEOS           PROJ             sp 
       "3.0.4"        "FALSE"        "7.1.0"        "1.4-1" 
```

Thank you for your guidance with this @rsbivand!
