### ISSUE TITLE
I always end up with 2 as nComponents in Scalar Analysis

### ISSUE THREAD

**Issue by Johnny987654321** [achubaty/grainscape#66]
I wonder why I always end up with 2 as the max Number of components when it should have been 1. I wonder what it means? I am using a raster data that only contains green areas (and all other values are NA) as my patch in creatin an MPG file. When I replaced the patches with a different raster data having four types of landuse I ended up with 4. Is that normal?

![nComponents](https://user-images.githubusercontent.com/82477758/117941431-5c07ec00-b30a-11eb-8a70-d81b8e574a1c.png)

**Comment by achubaty** [comment]
can you please provide a reporducible example?

**Comment by Johnny987654321** [comment]
I'm not sure how to do that but here are some codes I am using. The formaskSieve2 is the green patches extracted from the Raster data where patchy cost was created from. So while the patchyCost was the same raster data with resistance value the formaskSieve2 was just the green patches extracted with a value of 1 and NA.  I apologize for my lapses as I just copy my codes from the grainscape manual. 


patchyMPG <- MPG(patchyCost, patch= ( formaskSieve2== 1))

scalarAnalysis <- threshold(patchyMPG, weight = "lcpPerimWeight", nThresh = 10, doThresh = NULL)
kable(scalarAnalysis$summary,
      caption = paste("The number of components ('nComponents') in the",
                      "minimum planar graph at ten automatically-selected",
                      "link thresholds ('maxLink)."))


![Screen Shot 2021-05-13 at 6 44 28 AM](https://user-images.githubusercontent.com/82477758/118078555-be1e2b00-b3b6-11eb-8c1f-65e00fccf4e2.png)

**Comment by achubaty** [comment]
I just worked through this, and I think I reporduced what you were seeing:

```r
library(raster)
library(grainscape)

patchy <- raster(system.file("extdata/patchy.asc", package = "grainscape"))
isBecomes <- cbind(c(1, 2, 3, 4, 5), c(1, 10, 8, 3, 6))
patchyCost <- reclassify(patchy, rcl = isBecomes)

## orig version from vignette
patchyMPG0 <- MPG(patchyCost, patch = (patchyCost == 1))
scalarAnalysis0 <- threshold(patchyMPG0, weight = "lcpPerimWeight", nThresh = 5, doThresh = NULL)
scalarAnalysis0$summary

plot(patchyMPG0)
```

![image](https://user-images.githubusercontent.com/3435577/232978954-ca13d2a2-38b8-40b5-9c57-4041b63ed437.png)

```r
## your version
patchyMPG <- MPG(patchyCost, patch = (patchyCost == 6)) ## is this correct?
scalarAnalysis <- threshold(patchyMPG, weight = "lcpPerimWeight", nThresh = 10, doThresh = NULL)
scalarAnalysis$summary

plot(patchyMPG)
```

![image](https://user-images.githubusercontent.com/3435577/232978975-9f75370f-e8a4-4c73-9b09-87e56ac02b36.png)


As you can see from the figures, your version's MPG is two separate subgraphs, so I think this is correct behaviour.

I think we can close this issue, unless @ecologics disagrees.
